# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZdI1ArW5uA7FVsxv-Z5Ul8Upe0QCHT9w
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

st.set_page_config(page_title="AI Predictive Maintenance", layout="wide")
st.title("🏭 Physics-Informed Predictive Maintenance System")
st.markdown("""
This dashboard predicts machine failure by analyzing **Thermodynamic** and **Mechanical** stress limits.
It uses a **Random Forest** model enhanced with physics-based feature engineering.
""")

@st.cache_data # Caches the model so it doesn't retrain every time you move a slider
def train_model():
    df = pd.read_csv('ai4i2020.csv')

    # Feature Engineering (The Physics Formulas)
    df['Power_W'] = df['Torque [Nm]'] * df['Rotational speed [rpm]'] * (2 * np.pi / 60)
    df['Overstrain'] = df['Tool wear [min]'] * df['Torque [Nm]']
    df['Temp_Diff'] = df['Process temperature [K]'] - df['Air temperature [K]']

    features = ['Power_W', 'Overstrain', 'Temp_Diff', 'Tool wear [min]', 'Torque [Nm]']
    X = df[features]
    y = df['Machine failure']

    # Training
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model

with st.spinner('Calibrating Physics Model...'):
    model = train_model()
st.success("System Online. Model Calibrated.")

# Sidebar controls
st.sidebar.header("🔧 Machine Parameters")

# User inputs RAW values (What an operator sees)
torque = st.sidebar.slider("Torque [Nm]", 0, 80, 40)
rpm = st.sidebar.slider("Rotational Speed [RPM]", 1000, 3000, 1500)
tool_wear = st.sidebar.slider("Tool Wear [min]", 0, 300, 0)
process_temp = st.sidebar.slider("Process Temp [K]", 300, 320, 310)
air_temp = st.sidebar.slider("Air Temp [K]", 290, 310, 300)

# Backend Calculation
power_w = torque * rpm * (2 * np.pi / 60)
overstrain = tool_wear * torque
temp_diff = process_temp - air_temp

col1, col2, col3 = st.columns(3)
col1.metric("Calculated Power (P)", f"{int(power_w)} W", delta_color="inverse")
col2.metric("Thermal Delta (ΔT)", f"{temp_diff} K", delta_color="inverse")
col3.metric("Overstrain Load", f"{int(overstrain)} Units", delta_color="inverse")

#Prediction
input_data = pd.DataFrame({
    'Power_W': [power_w],
    'Overstrain': [overstrain],
    'Temp_Diff': [temp_diff],
    'Tool wear [min]': [tool_wear],
    'Torque [Nm]': [torque]
})

prediction = model.predict(input_data)[0]
probability = model.predict_proba(input_data)[0][1] # Probability of Failure

st.divider()

# Visualization
if probability > 0.5:
    st.error(f"🚨 FAILURE PREDICTED (Risk: {probability:.1%})")
    if temp_diff > 8.5:
        st.write("**Root Cause:** High Thermal Differential (Heat Dissipation Failure)")
    elif overstrain > 11000:
        st.write("**Root Cause:** Tool Overstrain (Fatigue Failure)")
    elif power_w > 9000: # Approximate threshold
        st.write("**Root Cause:** Power Overload")
else:
    st.success(f"✅ SYSTEM STABLE (Risk: {probability:.1%})")

# Simple Bar Chart for Risk
st.progress(probability)
