# -*- coding: utf-8 -*-
"""EngineFailureAnalysisAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WYVMB9R7ox2bpY5nKiAspyHQi28HDWP
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('ai4i2020.csv')
df = pd.DataFrame(data)
# df.info()
df.head()

if "Unamed:0" in df.columns:
  df=df.drop(columns=['Unamed:0'])

print(df.columns)

df.info()

#Distribution of data for various failures

print(f'Tool Wear Failure : {df['TWF'].sum()}')
print(f'Heat Dissipation Failure : {df['HDF'].sum()}')
print(f'Power Failure : {df['PWF'].sum()}')
print(f'Overstrain Failure : {df['OSF'].sum()}')
print(f'Random Failures : {df['RNF'].sum()}')

"""We can see that the data is not balanced for all the failure cases. So for training and evaluation we need to implement a model that is able to give good and accurate predictions for such type of dataset."""

#Preparing the dataset for train test split

df = df.drop(columns=['UDI', 'Product ID', 'Type', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF'], axis =1)
df.head()

#Spliting data and Training model
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score, accuracy_score

X_train, X_test, Y_train, Y_test = train_test_split(df.drop('Machine failure', axis=1), df['Machine failure'], test_size=0.2, random_state=42)


model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
model.fit(X_train, Y_train)

print("RandomForestClassifier Model training complete !")

# Evaluate
y_pred_rf = model.predict(X_test)
print(f'Accuracy: {accuracy_score(Y_test, y_pred_rf)}')
print(classification_report(Y_test, y_pred_rf))

"""### Project Part 1: Engine Failure Detection - Complete!

I'm excited to have successfully completed the first phase of this project, focusing on detecting engine failure. The model has shown promising results in identifying machine failures.

Next, I'm looking forward to extending this project to predict the *type* of failure, which will add even more valuable insights.
"""

